-- Browser-reviewed Google News snapshot rechecked 2026-08-01 15:29 Asia/Taipei.
-- No new valid event found; retained sixteen reviewed rows across twelve event clusters.
-- Primary query: https://news.google.com/search?q=(%E6%B0%B4%E7%94%A2%20OR%20%E6%BC%81%E6%A5%AD%E7%BD%B2%20OR%20%E6%B0%B4%E7%94%A2%E8%A9%A6%E9%A9%97%E6%89%80%20OR%20%E9%A4%8A%E6%AE%96%20OR%20%E6%BC%81%E6%B8%AF%20OR%20%E6%B0%B4%E7%94%A2%E5%93%81%20OR%20%E6%BC%81%E6%9D%91%20OR%20%E6%B5%B7%E6%B4%8B%E4%BF%9D%E8%82%B2%20OR%20%E5%9C%8B%E9%9A%9B%E6%BC%81%E6%A5%AD)%20-%E8%85%90%E5%B1%8D%20-%E7%94%B7%E5%B1%8D%20when%3A1d&hl=zh-TW&gl=TW&ceid=TW:zh-Hant
-- Government query: https://news.google.com/search?q=site%3Agov.tw%20(%E6%BC%81%E6%A5%AD%20OR%20%E6%B0%B4%E7%94%A2%20OR%20%E9%A4%8A%E6%AE%96%20OR%20%E6%BC%81%E6%B8%AF)%20when%3A1d&hl=zh-TW&gl=TW&ceid=TW:zh-Hant
-- International query: https://news.google.com/search?q=(aquaculture%20OR%20fisheries%20OR%20seafood%20OR%20%22IUU%20fishing%22%20OR%20%22fisheries%20governance%22)%20when%3A1d&hl=en-US&gl=US&ceid=US:en
-- This self-contained SQLite query reproduces the sixteen reviewed news rows used by artifact.json.
WITH news_items(
  id, cluster_id, hours_ago, priority, source, title, topic, sentiment, url,
  short_response, detailed_response
) AS (
  VALUES
('n1','c1',4,'低','蕃新聞','跟著海風趣蚵田！漁村體驗報名中','漁村體驗推廣','正向','https://news.google.com/read/CBMiUkFVX3lxTE9qNndRZFRhSlM1SW8yWk4xOVgzUm80MVhjOUh1YzFxM2NzNG1pdVBiMnVtLUtXbVpJMlA5Q2xyMEJXM2lVa1RYZVFCQmJaVE9IOGc?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','樂見漁村體驗增進民眾理解養殖環境；水試所將持續以科普與技術推廣，深化永續養蚵及食魚教育。','水試所樂見以蚵田體驗連結漁村文化、養殖知識與消費者教育。此類活動若能同步說明牡蠣生態、養殖環境承載、產品衛生、氣候風險與廢棄蚵架管理，可讓民眾更完整理解產業。水試所將持續提供科學資料與養殖技術，並與地方政府、漁會及產業團體合作推廣負責任養殖與食魚教育。活動執行仍應兼顧場域安全、生物安全及環境維護。'),
  ('n2','c2',5,'中','星島加拿大','卑詩男子非法持有珍貴漁獲 被罰款5500元禁釣一年','漁獲執法','負向','https://news.google.com/read/CBMijwFBVV95cUxNN25KbWh6emtwZnRKZk5maDYyX2RWNGdEa3RIVHdYNUZwSjhqOW9lR1VoN19hMW8zZ1hfUl9BOWRIT1Z6RmlCZVdEMEVFNnc1TUtRVlB5U2tUZ01SNmtQUDVIODczX2lWVlZiYUJocEZnUjdNM1FaM0xTb0xkTFJBRWVVZkJ6c0lkbjd1UGFRUQ?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','海外違法漁獲案件顯示科學配額、物種辨識與可追溯管理的重要；水試所將持續強化保育研究與技術支援。','本案屬加拿大司法與漁業管理範疇，水試所尊重當地權責機關認定。從科研與技術角度，珍貴或資源量偏低物種的管理需建立在族群評估、尺寸與季節限制、漁獲辨識及可追溯紀錄之上。水試所將持續精進臺灣重要水產資源調查、物種鑑定及數位監測技術，並協助漁民與消費端理解保育規範。個案裁罰不宜直接類比臺灣制度，但可作為法遵教育與風險溝通參考。'),
  ('n3','c3',14,'高','蕃新聞','臺美持續深化漁業合作 共同打擊IUU漁撈行為','國際漁業治理','中性','https://n.yam.com/Article/20260729250190','水試所支持以科學資料、追溯及監測技術強化臺美合作，共同提升IUU防制、資源永續與產業韌性。','水試所支持臺美就非法、未報告及不受規範（IUU）漁撈、漁業人權與國際參與深化合作。科研面可透過資源量評估、漁獲與混獲監測、物種鑑定、電子化紀錄及養殖技術交流，提供治理所需證據。報導亦提及續簽漁業及養殖合作備忘錄，以及輸美資格證明與海洋哺乳類保護規範等技術議題；水試所可在權責範圍內協助資料標準、監測方法與技術應用，並配合漁業署及相關機關提升透明度與國際信任。'),
  ('n4','c4',18,'低','壹電視','北市內湖水產店超佛心價冷凍水餃 一顆不到2元現已買嘸','消費市場','正向','https://news.google.com/read/CBMie0FVX3lxTFBtd1VwYjdVOWUwUFY3NjBvV3dzQUNyLVdjbmVHQVhhSEZsRjVsUFJoTlM2T1p5S2VENHVkYnZ4el8xM1dZSG9XcHZEb2FlQlNqZlVadUtDMjZtMm1EMGthS211MDV3Zk5fbmFBV2JvaUVaWXR6eFE3Z3JvVQ?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','價格話題反映消費關注；選購冷凍水產食品仍應確認標示、來源、保存與冷鏈，不宜僅以低價判斷品質。','本則主要屬零售價格與消費話題，僅憑售價無法判斷原料品質或安全。水試所建議消費者選購冷凍水產加工食品時，確認品名、成分、原產地、有效日期、保存條件及包裝完整性，並維持冷凍冷鏈、充分加熱。若涉及食品標示或安全查驗，應以衛生主管機關及業者正式資訊為準。水試所將持續推動水產品加工、保鮮與品質技術研究，協助產業提升產品穩定性與消費信任。'),
  ('n5','c5',20,'高','LINE TODAY／Newtalk','吃蟹注意！8/1起保護抱卵母蟹禁捕禁售 違者最高開罰15萬元','資源保育規範','中性','https://news.google.com/read/CBMiVkFVX3lxTE0xYVQ4Umdxd0RqQkU4MDVaT2JVR0wyRE9lN1NFd2JvcjFpLVpRT2hQaE5tUmlpemN2anZ6NjUtUE9rTE5jT1lIWmRTdFE2Y0hBSHRWZTB3?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','保護抱卵母蟹與小蟹有助資源補充；水試所將持續提供族群與繁殖研究，支持科學化管理及產業宣導。','蟳蟹繁殖期保護抱卵母蟹與未達規定尺寸個體，是維持資源補充與漁業永續的重要措施。水試所將持續進行生物學、繁殖週期、資源變動及棲地環境研究，提供管理措施調整所需科學依據；並協助開發物種與抱卵辨識、養殖繁育及資源復育技術。漁民、販售業者與消費者應依漁業署公告及地方權責機關說明辦理。涉及查緝與裁罰，則由主管機關依法認定。'),
  ('n6','c5',21,'高','中華新聞雲／中華日報','8/1起進入蟳蟹繁殖期 漁業署籲禁捕售小蟹與抱卵母蟹','資源保育規範','中性','https://news.google.com/read/CBMiUkFVX3lxTE9zUXIwSUlrYVBQaEU2TlFlMklrN3BQQVQwS2EwMzZTVFB4NHRSbHZBb2djZHhzek5vQjY0ZzI2YjlzdlB3OHBERy1Ka3J2SFlPWlE?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','水試所支持繁殖期保育措施，將以資源調查與繁養殖技術協助蟳蟹資源永續，並加強產業端辨識宣導。','水試所支持依科學證據推動蟳蟹繁殖期保育。禁捕售抱卵母蟹與小型個體，可降低成熟前與繁殖個體的捕撈壓力，讓族群有機會補充。後續應持續蒐集漁獲量、體長組成、抱卵比例、季節與海域差異等資料，評估措施成效並滾動調整。水試所亦將精進種苗繁育、養殖管理及資源復育研究，並與漁業署、地方政府、漁會及通路合作，協助第一線正確辨識與落實規範。'),
  ('n7','c6',2,'高','ESG遠見','從洗腎魚變身壽司主角！一條巴沙魚逆襲全球漁市','養殖市場與食安溝通','中性','https://esg.gvm.com.tw/article/94734','巴沙魚議題應回到檢驗與追溯證據；水試所將持續推動養殖、加工與品質研究，協助消費者辨識資訊。','以「洗腎魚」等標籤概括巴沙魚，容易造成污名與錯誤風險認知。報導引述食藥署資料指出，輸入水產品會接受重金屬、動物用藥及食品添加物抽驗，近期越南巴沙魚未見邊境檢驗不合格紀錄；個別產品安全仍應以主管機關檢驗、來源追溯與標示為準。水試所將持續投入養殖環境、魚種鑑別、加工保鮮與品質技術研究，協助產業提升透明度。面對氣候變遷與白肉魚供應結構改變，也應同步評估生產效率、環境承載、用藥管理與市場韌性。'),
('n8','c1',11,'中','金門日報','推廣傳統石蚵產業 水試所漁村體驗報名','漁村體驗推廣','正向','https://www.kmdn.gov.tw/1117/1271/1272/589047','本活動由金門縣水試所辦理。中央水試所樂見石蚵科普，並將持續以研究與技術協助養殖永續。','本報導所稱「水試所」為金門縣水產試驗所，與中央農業部水產試驗所為不同機關，對外溝通應清楚區隔。活動規劃於古寧頭北山進行漁村走讀、潮間帶生態探索、石蚵養殖解說及料理體驗，有助民眾理解傳統產業與海洋環境的關係。中央水試所樂見地方推動水產科普，並可在權責範圍內就牡蠣養殖、環境承載、生物安全、產品品質及氣候調適提供研究與技術交流，支持文化保存與資源永續利用。'),
('n9','c7',18,'中','TDN台灣生活新聞','揮別毛胚屋！民代爭取經費活化漁港空間','漁港設施與地方治理','中性','https://news.google.com/read/CBMiUEFVX3lxTE03WlgxeThyT0p1WnNiRC02UlVSSVdQeVF2X3RBTjJnS3pUUDVLM2lqQ2JjdTlwSmNBSUphWS1Xa2tNcUxiWkF6RFE1WThzUEtP?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','漁港活化應優先維持作業與安全功能，兼顧冷鏈、防災、環境及公共使用；水試所可提供技術建議。','漁港空間活化若能改善產業服務與公共使用，具有地方發展效益；規劃仍應以漁業作業、安全及生產需求為優先，並納入卸魚動線、冷鏈衛生、防災韌性、廢棄物處理、能源效率與環境承載。水試所可在權責範圍內提供水產品保鮮、加工、養殖技術及環境監測等專業建議。由於目前可核實資訊主要為新聞標題，實際經費、設計內容與權責分工，仍應以地方政府及漁業主管機關正式資料為準。'),
  ('n10','c8',3,'中','udn女子漾／旅奇傳媒','從九孔池走向地方活化 返鄉十餘年的李勝興用一生守住貢寮的海洋未來','地方創生與養殖轉型','正向','https://woman.udn.com/woman/amp/story/123162/9657823','九孔池再利用結合地方創生與海洋教育值得關注；水試所可就養殖、生態承載與場域安全提供技術支持。','報導呈現返鄉者整建廢棄九孔養殖池、結合體驗旅遊與海洋保育的地方創生案例。水試所樂見既有養殖場域透過適當規劃重新創造公共與產業價值；再利用過程應先評估水質、結構安全、生態承載、生物安全、極端天候與廢棄物管理，並避免體驗活動干擾棲地或造成外來種風險。水試所可就九孔及相關水產養殖、健康管理、環境監測與科普內容提供技術交流，協助地方建立兼顧產業、教育與保育的長期營運模式。'),
  ('n11','c9',2,'中','自由時報','東港青年壯遊培訓外語導覽員推動漁村文化走向國際','漁村文化與人才培育','正向','https://news.google.com/read/CBMiZEFVX3lxTE1GVk42cjI2T1hCZmtsenVHS0g3bUs2UF9KeFhTLURjTlV2RWNteEtFZ044dXI0Z1I2RTZra0RVV0NQc1FzMWhfWlljazRwQXJxQzY2Z2RNbWtvSW52NTRmZHZGb24?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','漁村外語導覽培力有助產業文化國際溝通；水試所可提供科學內容與技術素材，提升導覽正確性。','報導標題顯示東港推動青年壯遊與外語導覽培訓，方向有助漁村文化、產業知識與國際旅客溝通。水試所可就漁業資源、養殖技術、水產品品質安全、海洋環境及氣候調適提供科學素材，並與地方政府、學校、漁會及社區協作，協助導覽內容兼具在地敘事與科學正確性。因本輪僅核實 Google 新聞標題與發布時間，課程內容、主辦單位及執行成效仍應以正式資料為準。'),
  ('n12','c10',0,'高','INQUIRER.net','SC ruling weakens fight against illegal fishing, group warns','國際漁業治理','負向','https://newsinfo.inquirer.net/2275215/sc-ruling-weakens-fight-against-illegal-fishing-group-warns','菲律賓漁船監控裁決凸顯VMS與電子回報的重要；水試所支持以科學資料、追溯及風險溝通強化治理。','本案屬菲律賓司法與漁業治理範疇，水試所尊重當地法院及主管機關權責。報導指出，當地最高法院裁決使商業漁船強制監控與電子回報規定失效，保育團體憂心影響IUU漁撈查緝、近岸小規模漁民保障、漁獲追溯與海難定位。對臺灣的參考在於，船位監測、電子漁獲資料及資源評估需有清楚法源、資料治理與比例原則支持。水試所可持續提供資源量、漁獲與混獲、棲地及物種鑑定等科研資料，並配合漁業署與相關機關強化技術驗證及國際交流；制度適用仍由權責機關依法決定。'),
  ('n13','c5',0,'高','Newtalk新聞','秋蟹季別亂抓！漁業署今起嚴禁捕撈抱卵母蟹：違規最高重罰15萬元','資源保育規範','中性','https://newtalk.tw/news/view/2026-08-01/1050702','水試所支持依科學證據推動蟳蟹繁殖期保育，並將持續資源調查與技術支援；查緝及裁罰由權責機關依法辦理。','報導重申8月1日至12月31日禁止捕撈、販售或陳列抱卵母蟹，並列出多種蟳蟹最小甲殼尺寸；相關規範與裁罰仍以漁業署公告及權責機關認定為準。水試所支持以長期資源調查、繁殖生物學與漁獲組成分析評估管理成效，並可配合漁業署、海巡署、地方政府與學術單位提供物種辨識、尺寸量測、資源評估及產業宣導等技術支援。報導所述平均漁獲量回穩，仍宜持續觀察年度、海域與物種差異，避免僅以單一總量指標判定資源完全恢復。'),
  ('n14','c5',0,'高','Yahoo新聞／Newtalk','秋蟹季別亂抓！漁業署今起嚴禁捕撈抱卵母蟹：違規最高重罰15萬元','資源保育規範','中性','https://news.google.com/read/CBMinANBVV95cUxNcWJaYk92WGE5SVk1UEJXLURvd0lva2ViWVgxZThyM0s2YVYxeXdQaHFZd2hPcTFhOTZITnE2eW5oT0tHa1dQU1ZFNFpNNkVUdnlBdkNqY3lWQmt0N2FacUhlM0NkY2VvQkY2ZG10WFZGTUs3WGx5Z1FtY3FDWTVGRFBXYjFWcUUxbmZ3N043OXhwQkZRWUxIRjl6WnJUYmFrTm5JLWwzMDRYeWQwZGlhSDNZOXRtaWFMdjZkRm5yeUk1bXoxSGFoS1lMMHRBODVrSXBLOGxmQi1sU3pSTGQ2WFZmMkhGM05BUE9oTGNKVTZtanJMQkEyZGlSUW5OcDNGVXpWUkswSHZUa2QxbnN3YXRpeUk5dExrcmp2T2VUZEdSb2JWLWJiTWtBcVBialJwYlNjd3FDMHVWNEZpeVREUHQwTnpBOThEZHlzS2F0ZndYQy1JNWxFdUdLTnJYX1dfS25hZG1iRjB0cXVZWU1obUVMdzh6Q3UzSl9xX1lOQU5TNDI1c1ZZZmVOUWE0SVZlMDE5WThfSEoyS3dE?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant','水試所支持依科學證據推動蟳蟹繁殖期保育，並將持續資源調查與技術支援；查緝及裁罰由權責機關依法辦理。','本則為 Yahoo 新聞轉載同一蟳蟹保育事件，已併入 c5 群組，避免將重複報導誤判為多個事件。報導重點涉及抱卵母蟹禁捕禁售、幼蟹尺寸限制與違規罰鍰；規範適用、查緝及裁罰仍由漁業署、海巡署及地方權責機關依法認定。水試所將持續以繁殖生物學、漁獲組成與資源量調查提供科學依據，並協助物種辨識、尺寸量測及產業宣導，使保育措施兼顧資源補充、漁業生計與市場溝通。'),
  ('n15','c11',7,'高','行政院公報資訊網','農業天然災害低利貸款項目及額度','養殖韌性與災害金融','中性','https://gazette.nat.gov.tw/EG_FileManager/eguploadpub/eg032122/ch07/type3/gov88/num22/images/Eg01.pdf','水試所關注養殖災損融資調整，將以災害調查、養殖韌性與復養技術支援產業；資格與額度依權責機關公告。','行政院公報公布農業天然災害低利貸款項目及額度，正式資料明列魚塭養殖項目，包含鰻魚等類別。此類金融措施有助受災養殖戶恢復生產，但申請資格、災損認定、額度、利率與期限應以農業主管機關及承貸機構正式公告為準。水試所可從水質與設施受損評估、生物安全、種苗與健康管理、復養時程及氣候韌性技術提供科研支援，並配合漁業署、地方政府與金融執行單位協助技術資訊傳遞，降低復養風險。'),
  ('n16','c12',9,'中','Reuters','Amazon sued by consumers over seafood sustainability claims','水產品永續標示與追溯','負向','https://www.reuters.com/business/media-telecom/amazon-sued-by-consumers-over-seafood-sustainability-claims-2026-07-31/','水產品永續標示應有可驗證證據與完整追溯；本案責任由司法認定，水試所將持續強化鑑別與技術支援。','Reuters 報導美國消費者針對 Amazon 銷售水產品所使用的「dolphin safe」「sustainable」「wild caught」等標示提起訴訟，指稱相關宣稱可能誤導。本案事實、標示是否違法及個案責任，應由美國法院與權責機關認定，水試所不作預判。對臺灣的參考在於，水產品永續宣稱宜建立於可稽核的漁獲或養殖來源、物種鑑別、供應鏈紀錄、第三方驗證與清楚標示。水試所可持續精進物種鑑定、產地與生產方式辨識、品質檢測及追溯技術，並配合漁業、食安與消費者保護權責機關，協助產業降低資訊落差與綠色宣稱風險。')
)
SELECT * FROM news_items ORDER BY hours_ago ASC;
